#!/usr/bin/bash

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export PtolemyPath=$dir

if [[ -f DWBA ]]; then
 dummy=10
else
 cp $dir/../DWBA .
fi

root -l $dir/PtolemyGUI.C
